# Generated by Django 3.0.5 on 2021-04-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
